framework:
  secret: '%env(APP_SECRET)%'
  #default_locale: en
  #csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: ~

  #esi: true
  #fragments: true
  php_errors:
    log: true

  cache:
    # Redis
    app: cache.adapter.redis
    default_redis_provider: '%env(WEB_REDIS_URL)%'
    pools:
      app.cache.circuit_breaker:
        public: true
        adapter: cache.app
        default_lifetime: 1000 # 100 seconds

sensio_framework_extra:
  request:
    converters: true
    disable: ['doctrine.orm', 'datetime']
